#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

# zzz should be the last boot script
# the last script will record the process boot finished flag
START=99

boot() {
    touch /tmp/zfinal
}
