#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

# commands for emitting messages to network in failsafe mode

indicate_failsafe_led () {
	set_state failsafe
}

check_failsafe_passwd() {
    while :;
    do
        echo "Enter password: ('q' for reboot)"
        stty -echo
        read PASSWD
        stty echo
        echo ""

        [ "$PASSWD" = "hos2016" ] && break

        [ "$PASSWD" = "q" ] && {
            reboot
            sleep 3
        }

    done
}

indicate_failsafe() {

    # add passwd check
    check_failsafe_passwd

	echo "- failsafe -"
	preinit_net_echo "Entering Failsafe!\n"
	indicate_failsafe_led
}

boot_hook_add failsafe indicate_failsafe
