#!/bin/sh /etc/rc.common

START=75

USE_PROCD=1
PROG=/usr/bin/um

start_service()
{
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn
	procd_close_instance
	echo "um start ..."
}

reload_service()
{
	ubus call user-manage reload
}

restart_service()
{
	stop_service
	sleep 3
	start_service
}
