#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service()
{
        procd_open_instance
        procd_set_param command /usr/sbin/uploadlog start
        procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger "tftplog"
}
