
cluster_cli:show_member.o  
	        $(CC) $(LDFLAGS) show_member.o -o cluster_cli  
show_member.o:show_member.c  
	        $(CC) $(CFLAGS) -c show_member.c  
			  
clean:  
	        rm *.o cluster_cli 
