#!/bin/sh /etc/rc.common

#START=19
USE_PROCD=1

ARP_PROXY_BIN=/usr/sbin/arp-proxy
ARP_PROXY_IF_LIST=/var/run/arpp/if_list

start_service()
{
	if [ ! -d "/var/run/arpp/" ] ; then
		mkdir /var/run/arpp
	fi
	procd_open_instance
	procd_set_param command "$ARP_PROXY_BIN"
	procd_set_param respawn
	procd_close_instance

	echo > $ARP_PROXY_IF_LIST
	for i in `ls /proc/sys/net/ipv4/neigh/ | grep br`
	do
		echo $i >> $ARP_PROXY_IF_LIST
	done

	config_load 'arp-proxy'
	local switch                                 

	config_get_bool switch default 'proxy_switch'

	if [ $switch -ne 0 ]; then                                                         
		/usr/sbin/arpp_cli service enable                                          
		/usr/sbin/arpp_cli reload

		echo 1 > /sys/module/arpp_kmod/parameters/arppm_switch
	else                                         
		echo 0 > /sys/module/arpp_kmod/parameters/arppm_switch

		/usr/sbin/arpp_cli service disable   
	fi
}

reload_service()
{
	if [ ! -d "/var/run/arpp/" ] ; then
		mkdir /var/run/arpp
	fi

	echo > $ARP_PROXY_IF_LIST
	for i in `ls /proc/sys/net/ipv4/neigh/ | grep br`
	do
		echo $i >> $ARP_PROXY_IF_LIST
	done

	config_load 'arp-proxy'
	local switch
	config_get_bool switch default 'proxy_switch' 

	echo "switch $switch"
	if [ $switch -ne 0 ]; then                                                         
		/usr/sbin/arpp_cli service enable                                          
		/usr/sbin/arpp_cli reload

		echo 1 > /sys/module/arpp_kmod/parameters/arppm_switch
	else                                         
		echo 0 > /sys/module/arpp_kmod/parameters/arppm_switch

		/usr/sbin/arpp_cli service disable   
	fi
}
