#!/bin/sh
rm -rf /var/run/config.check
mkdir -p /var/run/config.check
for config in /etc/config/*; do
	file=${config##*/}
	uci show "${file##*/}" > /var/run/config.check/$file
done
MD5FILE=/var/run/config.md5
[ -f $MD5FILE ] && {
	local network_reload_flag=0
	for c in `md5sum -c $MD5FILE 2>/dev/null| grep FAILED | cut -d: -f1`; do
		if [[ "$(basename $c)" = network ]] ||
			[[ "$(basename $c)" = wireless ]]; then
			if [ $network_reload_flag == 0 ]; then
				/etc/init.d/network reload >/dev/null 2>&1 &
				network_reload_flag=1
			fi
		else
                	ubus call service event "{ \"type\": \"config.change\", \"data\": { \"package\": \"$(basename $c)\" }}"
		fi
        done
}
md5sum /var/run/config.check/* > $MD5FILE
rm -rf /var/run/config.check
